# Setup
title:               Lanyon
tagline:             'Symbolic regression for population models'
description:         'Automated discovery of interpretable gravitational-wave population models'
# baseurl:             '_site/'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Kaze Wong and Miles Cranmer

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
